/**
 * Pre-fetched vehicle data for default vehicles
 *
 * This file contains static vehicle data fetched from the fueleconomy.gov API
 * to avoid making API calls on initial page load. This improves performance
 * and reduces the number of API requests.
 *
 * Data includes:
 * - Complete vehicle specifications for all default vehicles
 * - Current national average fuel prices
 * - Timestamp of when this data was generated
 *
 * To update this data, run the fetchDefaultVehicleData.js script and
 * regenerate this file with fresh API data.
 */

import { ApiVehicle, FuelPrices } from '../FuelEconomyTool/api';

export interface DefaultVehicleDataSet {
  vehicleData: Record<number, ApiVehicle>;
  fuelPrices: FuelPrices | null;
  generatedAt: string;
}

export const DEFAULT_VEHICLE_DATA: DefaultVehicleDataSet = {
  "vehicleData": {
    "47723": {
      "atvType": "Hybrid",
      "barrels08": "13.52318181818182",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 20,
      "city08U": "19.694",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "407",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "407.0",
      "comb08": 22,
      "comb08U": "21.8024",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-03-19T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.6,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SCRXT03.65PN",
            "id": "47723",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "SCRXT03.65PN",
            "id": "47723",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "501",
      "eng_dscr": "Mild Hybrid",
      "evMotor": "48V Li-Ion",
      "feScore": "5",
      "fuelCost08": "2050",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "5",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 25,
      "highway08U": "25.0847",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 47723,
      "lv2": "0",
      "lv4": "0",
      "make": "Ram",
      "mfrCode": "CRX",
      "model": "1500 2WD",
      "modifiedOn": "2025-02-19T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic 8-spd",
      "UCity": "24.8491",
      "UCityA": "0.0",
      "UHighway": "35.2975",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 2WD",
      "year": 2025,
      "youSaveSpend": "-2250",
      "baseModel": "1500",
      "sCharger": "",
      "tCharger": ""
    },
    "47956": {
      "atvType": "",
      "barrels08": "10.625357142857142",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 26,
      "city08U": "26.2835",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "312",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "312.0",
      "comb08": 28,
      "comb08U": "28.3206",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-05-29T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 1.5,
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SHNXT01.5N7S",
            "id": "47956",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "SHNXT01.5N7S",
            "id": "47956",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          }
        ]
      },
      "engId": "201",
      "eng_dscr": "SIDI",
      "evMotor": "",
      "feScore": "6",
      "fuelCost08": "1600",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "6",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 31,
      "highway08U": "31.2842",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 47956,
      "lv2": "0",
      "lv4": "0",
      "make": "Honda",
      "mfrCode": "HNX",
      "model": "CR-V AWD",
      "modifiedOn": "2024-08-07T00:00:00-04:00",
      "mpgData": "Y",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "34.1651",
      "UCityA": "0.0",
      "UHighway": "44.9885",
      "UHighwayA": "0.0",
      "VClass": "Small Sport Utility Vehicle 4WD",
      "year": 2025,
      "youSaveSpend": "0",
      "baseModel": "CR-V",
      "sCharger": "",
      "tCharger": "T"
    },
    "48118": {
      "atvType": "",
      "barrels08": "14.8755",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 18,
      "city08U": "17.6728",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "439",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "439.0",
      "comb08": 20,
      "comb08U": "20.2257",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-08-07T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.0,
      "drive": "Part-time 4-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SFMXT03.03U2",
            "id": "48118",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          },
          {
            "efid": "SFMXT03.03U2",
            "id": "48118",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "SFMXT03.03U2",
            "id": "48118",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "SFMXT03.03U2",
            "id": "48118",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          }
        ]
      },
      "engId": "11",
      "eng_dscr": "SIDI",
      "evMotor": "",
      "feScore": "4",
      "fuelCost08": "2250",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "4",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 25,
      "highway08U": "24.5623",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48118,
      "lv2": "0",
      "lv4": "0",
      "make": "Ford",
      "mfrCode": "FMX",
      "model": "Explorer AWD",
      "modifiedOn": "2024-11-18T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (S10)",
      "UCity": "22.1",
      "UCityA": "0.0",
      "UHighway": "34.5",
      "UHighwayA": "0.0",
      "VClass": "Standard Sport Utility Vehicle 4WD",
      "year": 2025,
      "youSaveSpend": "-3250",
      "baseModel": "Explorer",
      "sCharger": "",
      "tCharger": "T"
    },
    "48199": {
      "atvType": "Diesel",
      "barrels08": "13.73826923076923",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 23,
      "city08U": "23.444",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "399",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "399.0",
      "comb08": 26,
      "comb08U": "25.5092",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-08-25T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.0,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SGMXT03.0354",
            "id": "48199",
            "salesArea": "7",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV70",
            "stdText": "California LEV-III ULEV70"
          },
          {
            "efid": "SGMXT03.0354",
            "id": "48199",
            "salesArea": "3",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B70",
            "stdText": "Federal Tier 3 Bin 70"
          }
        ]
      },
      "engId": "501",
      "eng_dscr": "",
      "evMotor": "",
      "feScore": "5",
      "fuelCost08": "2100",
      "fuelCostA08": "0",
      "fuelType": "Diesel",
      "fuelType1": "Diesel",
      "fuelType2": "",
      "ghgScore": "5",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 29,
      "highway08U": "28.5871",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48199,
      "lv2": "0",
      "lv4": "0",
      "make": "Chevrolet",
      "mfrCode": "GMX",
      "model": "Silverado 2WD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic 10-spd",
      "UCity": "30.0826",
      "UCityA": "0.0",
      "UHighway": "44.963",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 2WD",
      "year": 2025,
      "youSaveSpend": "-2500",
      "baseModel": "Silverado",
      "sCharger": "",
      "tCharger": "T"
    },
    "48374": {
      "atvType": "EV",
      "barrels08": "0.0552",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "10.0",
      "charge240b": "0.0",
      "city08": 149,
      "city08U": "149.0465",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "22.6138",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 146,
      "comb08U": "145.6506",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "23.141",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-08-25T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SLMUV00.0NR1",
            "id": "48374",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          },
          {
            "efid": "SLMUV00.0NR1",
            "id": "48374",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          }
        ]
      },
      "engId": "16",
      "eng_dscr": "",
      "evMotor": "330 kW ACPM",
      "feScore": "10",
      "fuelCost08": "500",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 142,
      "highway08U": "141.7046",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "23.7854",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48374,
      "lv2": "0",
      "lv4": "32",
      "make": "Lucid",
      "mfrCode": "LMU",
      "model": "Air Pure RWD with 19 inch wheels",
      "modifiedOn": "2024-11-18T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "101",
      "range": "420",
      "rangeA": "",
      "rangeCity": "430.0",
      "rangeCityA": "0.0",
      "rangeHwy": "408.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "209.1",
      "UCityA": "0.0",
      "UHighway": "198.8",
      "UHighwayA": "0.0",
      "VClass": "Large Cars",
      "year": 2025,
      "youSaveSpend": "5500",
      "baseModel": "Air",
      "sCharger": "",
      "tCharger": ""
    },
    "48405": {
      "atvType": "EV",
      "barrels08": "0.072",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "8.0",
      "charge240b": "0.0",
      "city08": 123,
      "city08U": "122.92",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "27.4203",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 114,
      "comb08U": "113.7044",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "29.6426",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-08-25T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SVVXV00.0Z0B",
            "id": "48405",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          },
          {
            "efid": "SVVXV00.0Z0B",
            "id": "48405",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          }
        ]
      },
      "engId": "250",
      "eng_dscr": "",
      "evMotor": "185 and 220 kW PMSM",
      "feScore": "9",
      "fuelCost08": "650",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 104,
      "highway08U": "104.16",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "32.3589",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "26",
      "hpv": "89",
      "id": 48405,
      "lv2": "0",
      "lv4": "0",
      "make": "Polestar",
      "mfrCode": "VVX",
      "model": "2 Single Motor (19 Inch Wheels)",
      "modifiedOn": "2024-09-10T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "314",
      "rangeA": "",
      "rangeCity": "337.0",
      "rangeCityA": "0.0",
      "rangeHwy": "286.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "175.6",
      "UCityA": "0.0",
      "UHighway": "148.8",
      "UHighwayA": "0.0",
      "VClass": "Midsize Cars",
      "year": 2025,
      "youSaveSpend": "4750",
      "baseModel": "2",
      "sCharger": "",
      "tCharger": ""
    },
    "48422": {
      "atvType": "EV",
      "barrels08": "0.0936",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "15.0",
      "charge240b": "0.0",
      "city08": 93,
      "city08U": "92.9982",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "36.2426",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 87,
      "comb08U": "86.7778",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "38.8406",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-08-25T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "Part-time 4-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SRIVT00.0SEP",
            "id": "48422",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          },
          {
            "efid": "SRIVT00.0SEP",
            "id": "48422",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          }
        ]
      },
      "engId": "65",
      "eng_dscr": "",
      "evMotor": "264 and 264 kW ACPM",
      "feScore": "9",
      "fuelCost08": "850",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 80,
      "highway08U": "80.2198",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "42.0158",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48422,
      "lv2": "0",
      "lv4": "0",
      "make": "Rivian",
      "mfrCode": "RIV",
      "model": "R1T Dual Max (22in)",
      "modifiedOn": "2025-06-25T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "420",
      "rangeA": "",
      "rangeCity": "448.0",
      "rangeCityA": "0.0",
      "rangeHwy": "386.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "131.0",
      "UCityA": "0.0",
      "UHighway": "113.0",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 4WD",
      "year": 2025,
      "youSaveSpend": "3750",
      "baseModel": "R1T",
      "sCharger": "",
      "tCharger": ""
    },
    "48504": {
      "atvType": "",
      "barrels08": "9.2971875",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 29,
      "city08U": "29.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "277",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "277.0",
      "comb08": 32,
      "comb08U": "32.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-18T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 1.5,
      "drive": "Front-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SHNXV01.56EB",
            "id": "48504",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          },
          {
            "efid": "SHNXV01.56EB",
            "id": "48504",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          }
        ]
      },
      "engId": "101",
      "eng_dscr": "SIDI",
      "evMotor": "",
      "feScore": "6",
      "fuelCost08": "1400",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "6",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 37,
      "highway08U": "37.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48504,
      "lv2": "0",
      "lv4": "17",
      "make": "Honda",
      "mfrCode": "HNX",
      "model": "Accord",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "106",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "39.1495",
      "UCityA": "0.0",
      "UHighway": "55.7109",
      "UHighwayA": "0.0",
      "VClass": "Large Cars",
      "year": 2025,
      "youSaveSpend": "1000",
      "baseModel": "Accord",
      "sCharger": "",
      "tCharger": "T"
    },
    "48505": {
      "atvType": "Hybrid",
      "barrels08": "6.198125",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 51,
      "city08U": "51.2938",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "184",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "184.0",
      "comb08": 48,
      "comb08U": "48.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-18T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.0,
      "drive": "Front-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SHNXV02.07EB",
            "id": "48505",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "SHNXV02.07EB",
            "id": "48505",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "121",
      "eng_dscr": "SIDI; Hybrid",
      "evMotor": "259V Li-Ion",
      "feScore": "8",
      "fuelCost08": "950",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "8",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 44,
      "highway08U": "44.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48505,
      "lv2": "0",
      "lv4": "17",
      "make": "Honda",
      "mfrCode": "HNX",
      "model": "Accord Hybrid",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "106",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "72.4",
      "UCityA": "0.0",
      "UHighway": "66.9",
      "UHighwayA": "0.0",
      "VClass": "Large Cars",
      "year": 2025,
      "youSaveSpend": "3250",
      "baseModel": "Accord",
      "sCharger": "",
      "tCharger": ""
    },
    "48507": {
      "atvType": "",
      "barrels08": "9.917",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 27,
      "city08U": "26.8711",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "300",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "300.0",
      "comb08": 30,
      "comb08U": "30.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-18T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.5,
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SFHIV02.5F9V",
            "id": "48507",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "SFHIV02.5F9V",
            "id": "48507",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "201",
      "eng_dscr": "",
      "evMotor": "",
      "feScore": "6",
      "fuelCost08": "1500",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "6",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 35,
      "highway08U": "35.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48507,
      "lv2": "0",
      "lv4": "0",
      "make": "Subaru",
      "mfrCode": "FHI",
      "model": "Impreza AWD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "34.4",
      "UCityA": "0.0",
      "UHighway": "49.0",
      "UHighwayA": "0.0",
      "VClass": "Compact Cars",
      "year": 2025,
      "youSaveSpend": "500",
      "baseModel": "Impreza",
      "sCharger": "",
      "tCharger": ""
    },
    "48510": {
      "atvType": "Hybrid",
      "barrels08": "12.01090909090909",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 22,
      "city08U": "21.9668",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "369",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "369.0",
      "comb08": 22,
      "comb08U": "22.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-19T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.5,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STMCT03.5M1K",
            "id": "48510",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "STMCT03.5M1K",
            "id": "48510",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          }
        ]
      },
      "engId": "103",
      "eng_dscr": "Hybrid",
      "evMotor": "245V Li-Ion",
      "feScore": "5",
      "fuelCost08": "2050",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "5",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 24,
      "highway08U": "24.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48510,
      "lv2": "0",
      "lv4": "0",
      "make": "Toyota",
      "mfrCode": "TMC",
      "model": "Tundra 2WD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic 10-spd",
      "UCity": "27.7",
      "UCityA": "0.0",
      "UHighway": "33.7",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 2WD",
      "year": 2025,
      "youSaveSpend": "-2250",
      "baseModel": "Tundra",
      "sCharger": "",
      "tCharger": "T"
    },
    "48581": {
      "atvType": "Hybrid",
      "barrels08": "20.5878125",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 12,
      "city08U": "11.3664",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "682",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "682.0",
      "comb08": 14,
      "comb08U": "14.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-19T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 12,
      "displ": 6.5,
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SLMBT06.5A7Z",
            "id": "48581",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "SLMBT06.5A7Z",
            "id": "48581",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          }
        ]
      },
      "engId": "801",
      "eng_dscr": "SIDI; Hybrid",
      "evMotor": "400V Li-Ion",
      "feScore": "2",
      "fuelCost08": "3800",
      "fuelCostA08": "0",
      "fuelType": "Premium",
      "fuelType1": "Premium Gasoline",
      "fuelType2": "",
      "ghgScore": "1",
      "ghgScoreA": "-1",
      "guzzler": "G",
      "highway08": 18,
      "highway08U": "18.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48581,
      "lv2": "0",
      "lv4": "0",
      "make": "Lamborghini",
      "mfrCode": "LMB",
      "model": "Revuelto",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (S8)",
      "UCity": "14.2",
      "UCityA": "0.0",
      "UHighway": "25.2",
      "UHighwayA": "0.0",
      "VClass": "Two Seaters",
      "year": 2025,
      "youSaveSpend": "-9000",
      "baseModel": "Revuelto",
      "sCharger": "",
      "tCharger": "T"
    },
    "48658": {
      "atvType": "Hybrid",
      "barrels08": "17.9875",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 13,
      "city08U": "13.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "596",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "596.0",
      "comb08": 16,
      "comb08U": "16.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-20T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.0,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SFRRT02.99CA",
            "id": "48658",
            "salesArea": "3",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B70",
            "stdText": "Federal Tier 3 Bin 70"
          },
          {
            "efid": "SFRRT02.99CA",
            "id": "48658",
            "salesArea": "7",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV70",
            "stdText": "California LEV-III ULEV70"
          }
        ]
      },
      "engId": "201",
      "eng_dscr": "SIDI; Hybrid",
      "evMotor": "670V Li-Ion",
      "feScore": "2",
      "fuelCost08": "3350",
      "fuelCostA08": "0",
      "fuelType": "Premium",
      "fuelType1": "Premium Gasoline",
      "fuelType2": "",
      "ghgScore": "2",
      "ghgScoreA": "-1",
      "guzzler": "G",
      "highway08": 21,
      "highway08U": "21.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48658,
      "lv2": "0",
      "lv4": "0",
      "make": "Ferrari",
      "mfrCode": "FRR",
      "model": "296 GTB",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (S8)",
      "UCity": "16.2",
      "UCityA": "0.0",
      "UHighway": "29.4",
      "UHighwayA": "0.0",
      "VClass": "Two Seaters",
      "year": 2025,
      "youSaveSpend": "-7750",
      "baseModel": "296 GTB",
      "sCharger": "",
      "tCharger": "T"
    },
    "48764": {
      "atvType": "EV",
      "barrels08": "0.0732",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "10.0",
      "charge240b": "0.0",
      "city08": 135,
      "city08U": "134.682",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "24.9815",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 120,
      "comb08U": "120.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "28.1089",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-20T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STSLV00.0Z93",
            "id": "48764",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          },
          {
            "efid": "STSLV00.0Z93",
            "id": "48764",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          }
        ]
      },
      "engId": "801",
      "eng_dscr": "",
      "evMotor": "170 and 236 kW PMSM",
      "feScore": "9",
      "fuelCost08": "650",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 104,
      "highway08U": "104.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "32.3589",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48764,
      "lv2": "0",
      "lv4": "32",
      "make": "Tesla",
      "mfrCode": "TSL",
      "model": "Model 3 Long Range AWD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "101",
      "range": "363",
      "rangeA": "",
      "rangeCity": "390.0",
      "rangeCityA": "0.0",
      "rangeHwy": "329.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "176.0",
      "UCityA": "0.0",
      "UHighway": "148.8",
      "UHighwayA": "0.0",
      "VClass": "Midsize Cars",
      "year": 2025,
      "youSaveSpend": "4750",
      "baseModel": "Model 3",
      "sCharger": "",
      "tCharger": ""
    },
    "48809": {
      "atvType": "",
      "barrels08": "13.738",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 18,
      "city08U": "18.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "429",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "429.0",
      "comb08": 21,
      "comb08U": "21.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-27T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.0,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SPRST02.036J",
            "id": "48809",
            "salesArea": "3",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B70",
            "stdText": "Federal Tier 3 Bin 70"
          },
          {
            "efid": "SPRST02.036J",
            "id": "48809",
            "salesArea": "7",
            "score": "4.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV70",
            "stdText": "California LEV-III ULEV70"
          }
        ]
      },
      "engId": "101",
      "eng_dscr": "SIDI",
      "evMotor": "",
      "feScore": "3",
      "fuelCost08": "2550",
      "fuelCostA08": "0",
      "fuelType": "Premium",
      "fuelType1": "Premium Gasoline",
      "fuelType2": "",
      "ghgScore": "4",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 26,
      "highway08U": "26.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48809,
      "lv2": "0",
      "lv4": "0",
      "make": "Porsche",
      "mfrCode": "PRS",
      "model": "718 Boxster",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (AM7)",
      "UCity": "22.5",
      "UCityA": "0.0",
      "UHighway": "36.5",
      "UHighwayA": "0.0",
      "VClass": "Two Seaters",
      "year": 2025,
      "youSaveSpend": "-4750",
      "baseModel": "718 Boxster",
      "sCharger": "",
      "tCharger": "T"
    },
    "48861": {
      "atvType": "Hybrid",
      "barrels08": "5.2325",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 57,
      "city08U": "56.874",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "155",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "155.0",
      "comb08": 57,
      "comb08U": "57.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-27T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.0,
      "drive": "Front-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STMCV02.007K",
            "id": "48861",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "STMCV02.007K",
            "id": "48861",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "501",
      "eng_dscr": "Hybrid",
      "evMotor": "177.6V Li-Ion",
      "feScore": "9",
      "fuelCost08": "800",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "9",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 56,
      "highway08U": "56.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48861,
      "lv2": "0",
      "lv4": "0",
      "make": "Toyota",
      "mfrCode": "TMC",
      "model": "Prius",
      "modifiedOn": "2024-11-18T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "80.3",
      "UCityA": "0.0",
      "UHighway": "78.4",
      "UHighwayA": "0.0",
      "VClass": "Midsize Cars",
      "year": 2025,
      "youSaveSpend": "4000",
      "baseModel": "Prius",
      "sCharger": "",
      "tCharger": ""
    },
    "48884": {
      "atvType": "Hybrid",
      "barrels08": "12.449090909090908",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 21,
      "city08U": "21.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "382",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "382.0",
      "comb08": 22,
      "comb08U": "22.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-27T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 6,
      "displ": 3.5,
      "drive": "Rear-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SFMXT03.5P6A",
            "id": "48884",
            "salesArea": "3",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B50",
            "stdText": "Federal Tier 3 Bin 50"
          },
          {
            "efid": "SFMXT03.5P6A",
            "id": "48884",
            "salesArea": "7",
            "score": "5.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3ULEV50",
            "stdText": "California LEV-III ULEV50"
          }
        ]
      },
      "engId": "101",
      "eng_dscr": "SIDI; Hybrid",
      "evMotor": "45 kW 48V Li-Ion",
      "feScore": "5",
      "fuelCost08": "2050",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "5",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 25,
      "highway08U": "25.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48884,
      "lv2": "0",
      "lv4": "0",
      "make": "Ford",
      "mfrCode": "FMX",
      "model": "F150 Pickup 2WD",
      "modifiedOn": "2024-11-06T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic 10-spd",
      "UCity": "26.3",
      "UCityA": "0.0",
      "UHighway": "35.1",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 2WD",
      "year": 2025,
      "youSaveSpend": "-2250",
      "baseModel": "F150",
      "sCharger": "",
      "tCharger": "T"
    },
    "48910": {
      "atvType": "",
      "barrels08": "12.449090909090908",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 25,
      "city08U": "25.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "382",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "382.0",
      "comb08": 27,
      "comb08U": "27.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-27T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.5,
      "drive": "Front-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STMCV02.5M9K",
            "id": "48910",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "STMCV02.5M9K",
            "id": "48910",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "-1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "101",
      "eng_dscr": "",
      "evMotor": "",
      "feScore": "6",
      "fuelCost08": "1700",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "5",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 32,
      "highway08U": "32.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48910,
      "lv2": "0",
      "lv4": "0",
      "make": "Toyota",
      "mfrCode": "TMC",
      "model": "RAV4 FWD",
      "modifiedOn": "2024-11-18T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic 8-spd",
      "UCity": "33.7",
      "UCityA": "0.0",
      "UHighway": "44.8",
      "UHighwayA": "0.0",
      "VClass": "Small Sport Utility Vehicle 2WD",
      "year": 2025,
      "youSaveSpend": "-500",
      "baseModel": "RAV4",
      "sCharger": "",
      "tCharger": ""
    },
    "48937": {
      "atvType": "Hybrid",
      "barrels08": "7.47025",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "0.0",
      "charge240b": "0.0",
      "city08": 42,
      "city08U": "42.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "0.0",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "223",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "223.0",
      "comb08": 40,
      "comb08U": "40.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "0.0",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-09-27T00:00:00-04:00",
      "cylDeact": "N",
      "cylDeactYesNo": "No",
      "cylinders": 4,
      "displ": 2.5,
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STMCV02.5M9K",
            "id": "48937",
            "salesArea": "3",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "T3B30",
            "stdText": "Federal Tier 3 Bin 30"
          },
          {
            "efid": "STMCV02.5M9K",
            "id": "48937",
            "salesArea": "7",
            "score": "6.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "1",
            "standard": "L3SULEV30",
            "stdText": "California LEV-III SULEV30"
          }
        ]
      },
      "engId": "121",
      "eng_dscr": "Hybrid",
      "evMotor": "259V NiMH",
      "feScore": "8",
      "fuelCost08": "1150",
      "fuelCostA08": "0",
      "fuelType": "Regular",
      "fuelType1": "Regular Gasoline",
      "fuelType2": "",
      "ghgScore": "7",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 38,
      "highway08U": "38.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "0.0",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 48937,
      "lv2": "0",
      "lv4": "0",
      "make": "Toyota",
      "mfrCode": "TMC",
      "model": "RAV4 Hybrid AWD",
      "modifiedOn": "2024-11-18T00:00:00-05:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "0",
      "rangeA": "",
      "rangeCity": "0.0",
      "rangeCityA": "0.0",
      "rangeHwy": "0.0",
      "rangeHwyA": "0.0",
      "startStop": "Y",
      "trans_dscr": "",
      "trany": "Automatic (variable gear ratios)",
      "UCity": "59.3",
      "UCityA": "0.0",
      "UHighway": "53.2",
      "UHighwayA": "0.0",
      "VClass": "Small Sport Utility Vehicle 4WD",
      "year": 2025,
      "youSaveSpend": "2250",
      "baseModel": "RAV4",
      "sCharger": "",
      "tCharger": ""
    },
    "49077": {
      "atvType": "EV",
      "barrels08": "0.1284",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "19.0",
      "charge240b": "0.0",
      "city08": 66,
      "city08U": "66.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "51.1267",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 66,
      "comb08U": "66.0",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "51.1267",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-10-03T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "Part-time 4-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "SFMXT00.0RJ2",
            "id": "49077",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          },
          {
            "efid": "SFMXT00.0RJ2",
            "id": "49077",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          }
        ]
      },
      "engId": "501",
      "eng_dscr": "",
      "evMotor": "145 and 208 kW ACPM",
      "feScore": "7",
      "fuelCost08": "1150",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 66,
      "highway08U": "66.0",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "51.1267",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 49077,
      "lv2": "0",
      "lv4": "0",
      "make": "Ford",
      "mfrCode": "FMX",
      "model": "F-150 Lightning 4WD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "260",
      "rangeA": "",
      "rangeCity": "270.0",
      "rangeCityA": "0.0",
      "rangeHwy": "250.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "93.0",
      "UCityA": "0.0",
      "UHighway": "93.0",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 4WD",
      "year": 2025,
      "youSaveSpend": "2250",
      "baseModel": "F-150 Lightning",
      "sCharger": "",
      "tCharger": ""
    },
    "49152": {
      "atvType": "EV",
      "barrels08": "0.1356",
      "barrelsA08": "0.0",
      "battery": "-1",
      "c240Dscr": "",
      "c240bDscr": "",
      "charge120": "0.0",
      "charge240": "15.0",
      "charge240b": "0.0",
      "city08": 63,
      "city08U": "63.0",
      "cityA08": "0",
      "cityA08U": "0.0",
      "cityCD": "0.0",
      "cityE": "53.4949",
      "cityMpk": "0",
      "cityUF": "0.0",
      "cityUmpk": "0.0",
      "co2": "0",
      "co2A": "-1",
      "co2TailpipeAGpm": "0.0",
      "co2TailpipeGpm": "0.0",
      "comb08": 63,
      "comb08U": "62.685",
      "combA08": "0",
      "combA08U": "0.0",
      "combE": "53.4949",
      "combMpk": "0",
      "combUmpk": "0.0",
      "combinedCD": "0.0",
      "combinedUF": "0.0",
      "createdOn": "2024-10-11T00:00:00-04:00",
      "cylDeact": "",
      "cylDeactYesNo": "No",
      "cylinders": "",
      "displ": "",
      "drive": "All-Wheel Drive",
      "emissionsList": {
        "emissionsInfo": [
          {
            "efid": "STSLT00.000A",
            "id": "49152",
            "salesArea": "3",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "T3B0",
            "stdText": "Federal Tier 3 Bin 0"
          },
          {
            "efid": "STSLT00.000A",
            "id": "49152",
            "salesArea": "7",
            "score": "10.0",
            "scoreAlt": "-1.0",
            "smartwayScore": "2",
            "standard": "ZEV",
            "stdText": "California ZEV"
          }
        ]
      },
      "engId": "14",
      "eng_dscr": "",
      "evMotor": "NA",
      "feScore": "7",
      "fuelCost08": "1200",
      "fuelCostA08": "0",
      "fuelType": "Electricity",
      "fuelType1": "Electricity",
      "fuelType2": "",
      "ghgScore": "10",
      "ghgScoreA": "-1",
      "guzzler": "",
      "highway08": 62,
      "highway08U": "61.685",
      "highwayA08": "0",
      "highwayA08U": "0.0",
      "highwayCD": "0.0",
      "highwayE": "54.4356",
      "highwayMpk": "0",
      "highwayUF": "0.0",
      "highwayUmpk": "0.0",
      "hlv": "0",
      "hpv": "0",
      "id": 49152,
      "lv2": "0",
      "lv4": "0",
      "make": "Tesla",
      "mfrCode": "TSL",
      "model": "Cybertruck AWD",
      "modifiedOn": "2024-10-17T00:00:00-04:00",
      "mpgData": "N",
      "mpgRevised": "false",
      "phevBlended": "false",
      "phevCity": "0",
      "phevComb": "0",
      "phevHwy": "0",
      "pv2": "0",
      "pv4": "0",
      "range": "318",
      "rangeA": "",
      "rangeCity": "322.0",
      "rangeCityA": "0.0",
      "rangeHwy": "313.0",
      "rangeHwyA": "0.0",
      "startStop": "N",
      "trans_dscr": "",
      "trany": "Automatic (A1)",
      "UCity": "88.0",
      "UCityA": "0.0",
      "UHighway": "86.0",
      "UHighwayA": "0.0",
      "VClass": "Standard Pickup Trucks 4WD",
      "year": 2025,
      "youSaveSpend": "2000",
      "baseModel": "Cybertruck",
      "sCharger": "",
      "tCharger": ""
    }
  },
  "fuelPrices": {
    "cng": "2.11",
    "diesel": "3.47",
    "e85": "2.63",
    "electric": "0.15",
    "lpg": "3.18",
    "midgrade": "4.37",
    "premium": "4.75",
    "regular": "3.98"
  },
  "generatedAt": "2025-11-06T00:00:00.000Z"
};
